config/routes.rb
Rails.application.routes.draw do

  resources :tips, only: [:index, :show]
  resources :contributions

  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get '/auth/failure' => 'sessions#failure'
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user, optional: true

  has_attached_file :image, styles: {
    medium: "300x300>", thumb: "100x100>"
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/tip.rb
class Tip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :contributions

  validates :provider, :uid, presence: true

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name']
        user.email = auth['info']['email']
        user.image_url = auth['info']['image']
      end
      if auth['credentials']
        user.credential_token = auth['credentials']['token']
        user.credential_expires_at = auth['credentials']['expires_at']
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def authenticate_user!
    if !current_user
      if Rails.env.production?
        redirect_to signin_path
      else
        redirect_to '/auth/developer'
      end
    end
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :destroy]

  def index
    @contributions = current_user.contributions
  end

  def show
    @contribution = current_user.contributions.find(params[:id])
  end

  def edit
    @contribution = Contribution.find(params[:id])
  end

  def create
    @contribution = Contribution.new(contribution_params)
    if @contribution.save
      redirect_to edit_contribution_path(@contribution)
    end
  end

  def update
    @contribution = Contribution.find(params[:id])
    if current_user
      @contribution.user = current_user
    end
    @contribution.update(contribution_params)
    redirect_to root_path
  end

  def destroy
    contribution = current_user.contributions.find(params[:id])
    contribution.destroy
  end

  private

  def contribution_params
    params.require(:contribution).
           permit(:image, :container)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def new
    redirect_to '/auth/facebook'
  end

  def create
    user = User.find_by(
      provider: auth_hash['provider'],
      uid: auth_hash['uid'].to_s
    ) || User.create_with_omniauth(auth_hash)
    reset_session
    session[:user_id] = user.id

    redirect_to request.env['omniauth.origin'] || root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def failure
    redirect_to root_path, alert: "Error: #{params[:message].humanize}"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    if params[:q].present?
      tip = Tip.where(
        "tips.title ILIKE ? OR tips.body ILIKE ?" ,
        "%#{params[:q]}%", "%#{params[:q]}%"
      ).first
      render json: tip
    else
      @tips = Tip.all
    end
  end

  def show
    @tip = Tip.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper

  def tip_of_the_day
    Tip.all.sample
  end

end

app/views/contributions/_form.html.erb
<%= form_for(contribution) do |f| %>
  <div class="field">
    <%= f.radio_button :container, :papel %> papel
    <%= f.radio_button :container, :plastico %> plastico
    <%= f.radio_button :container, :vidro %> vidro
    <%= f.radio_button :container, :metal %> metal
    <%= f.radio_button :container, :organico %> organico
  </div>
  <div class="actions">
    <%= f.submit 'ok' %>
  </div>
<% end %>

<hr>

<div class="dailyTips">
</div>

app/views/contributions/create.html.erb
<h1>Contributions#create</h1>
<p>Find me in app/views/contributions/create.html.erb</p>

app/views/contributions/destroy.html.erb
<h1>Contributions#destroy</h1>
<p>Find me in app/views/contributions/destroy.html.erb</p>

app/views/contributions/edit.html.erb
<%= image_tag @contribution.image.url(:medium) %>
<%= render 'form', contribution: @contribution %>

<% unless current_user %>
  <% if Rails.env.production? %>
    <%= link_to 'Entre com o facebook para guardar esta foto', signin_path %>
  <% else %>
    <%= link_to 'Entre com o facebook para guardar esta foto', '/auth/developer' %>
  <% end %>
<% end %>

app/views/contributions/index.html.erb
<%= link_to 'Terminar sessão', signout_path %>

<% @contributions.each do |contribution| %>
  <div>
    <%= image_tag contribution.image.url(:medium) %>
    <p><%= contribution.container %></p>
  </div>
<% end %>

app/views/contributions/show.html.erb
<%= image_tag @contribution.image.url(:medium) %>
<strong><%= @contribution.container %></strong>
<p><%= @contribution.processing_results %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripleR</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '290997551349003',
          cookie     : true,
          xfbml      : true,
          version    : 'v2.8'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <header>
      <nav class="navbar">
        <ul>
          <li class="home icon"><a href="<%= root_path %>"></a></li>
          <li class="tips icon"><a href="<%= tips_path %>"></a></li>
          <li class="profile icon"><a href="<%= contributions_path %>"></a></li>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1><strong>T</strong>riple<strong>R</strong></h1>
<p class="greeting"><strong>R</strong>eutilar <strong>R</strong>eduzir <strong>R</strong>eciclar</p>

<%= render "shared/recycleBins" %>

<section class="dailyTips">
  <h2><a href="<%= tips_path %>"><%= tip_of_the_day.title %></a></h2>
  <a href="<%= tips_path %>"><%= image_tag tip_of_the_day.image_url %></a>
  <p><%= tip_of_the_day.body %></p>
</section>

<hr>

<%= form_for(Contribution.new, multipart: true) do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class:"btnCamera" %>
  </div>
  <div class="actions">
    <%= f.submit 'Upload' %>
  </div>
<% end %>

app/views/shared/_recycleBins.html.erb
<section class="recycle">
  <div class="recycleBin papel">
    <span class="thumbsUp"></span>
    <p>papel</p>
  </div>
  <div class="recycleBin plastico">
    <span class="thumbsUp"></span>
    <p>plástico</p>
  </div>
  <div class="recycleBin vidro">
    <span class="thumbsUp"></span>
    <p>vidro</p>
  </div>
  <div class="recycleBin metal">
    <span class="thumbsUp"></span>
    <p>metal</p>
  </div>
  <div class="recycleBin organico">
    <span class="thumbsUp"></span>
    <p>orgânico</p>
  </div>

</section>

app/views/tips/index.html.erb
<% @tips.each do |tip| %>
  <div class="dailyTips">
    <h2><a href="<%= tips_path %>"><%= tip.title %></a></h2>
    <a href="<%= tips_path %>"><%= image_tag tip.image_url %></a>
    <p><%= tip.body %></p>
  </div>
<% end %>

app/views/tips/show.html.erb
<div>
  <strong><%= @tip.title %></strong>
  <%= image_tag @tip.image_url %>
  <p><%= @tip.body %></p>
</div>